---
name: 'Rebel Media GIT Config'
description: 'Configure GIT to use a set user account and sign with GPG.'
author: 'Rebel Media'

branding:
  icon: terminal
  color: black

inputs:
  git_user_name:
    type: string
    description: GIT username
    required: true
  git_user_email:
    type: string
    description: GIT user email
    required: true
  git_gpg_key:
    type: string
    description: GPG Key
    required: true
  git_gpg_key_id:
    type: string
    description: GPG key ID
    required: true

runs:
  using: composite
  steps:

    - name: Import GPG key
      shell: bash
      run: |
        echo -n "$GPG_KEY" | base64 --decode | gpg --import
      env:
        GPG_KEY: ${{ inputs.git_gpg_key }}

    - name: Setup GIT
      shell: bash
      run: |
        git config user.name ${{ inputs.git_user_name }}
        git config user.email ${{ inputs.git_user_email }}
        git config commit.gpgsign true
        git config user.signingkey $GPG_KEY_ID
      env:
        GPG_KEY_ID: ${{ inputs.git_gpg_key_id }}
